apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: traceassist
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      # # --- FIX: Point to our new, stable loki-service ---
      # loki:
      #   endpoint: "http://loki-service.loki.svc.cluster.local:3100/loki/api/v1/push"
      #   tls:
      #     insecure: true

      otlp/jaeger:
        endpoint: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
        tls:
          insecure: true
      
      prometheusremotewrite:
        endpoint: "http://prometheus-server.prometheus.svc.cluster.local/api/v1/write"
        tls:
          insecure: true

    processors:
      batch: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        # logs:
        #   receivers: [otlp]
        #   processors: [batch]
        #   exporters: [loki]
