apiVersion: v1
kind: Service
metadata:
  name: traceassist-collector
  namespace: traceassist
spec:
  ports:
    - name: grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    app: traceassist-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-collector
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-collector
  template:
    metadata:
      labels:
        app: traceassist-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command:
        - "/otelcol-contrib"
        - "--config=/conf/otel-collector-config"
        ports:
        - name: grpc
          containerPort: 4317
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /conf
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
